import {Card} from '@shared/types/Card/Card';

export const CardsTest: Card[] = [
  {
    card_id: 123,
    reviewer_id: 123,
    name: 'first Card',
    reward: 123,
    photo_required: false,
    video_required: false,
    schedule: [],
    period_start: null,
    period_stop: null,
    type: 'TASKS',
    description: null,
    every_month: [],
  },
  {
    card_id: 345,
    reviewer_id: 123,
    name: 'second Card',
    reward: 123,
    photo_required: false,
    video_required: false,
    schedule: [],
    period_start: null,
    period_stop: null,
    type: 'TASKS',
    description: null,
    every_month: [],
  },
  {
    card_id: 567,
    reviewer_id: 123,
    name: 'string',
    reward: 123,
    photo_required: false,
    video_required: false,
    schedule: [],
    period_start: null,
    period_stop: null,
    type: 'ALL',
    description: null,
    every_month: [],
  },
];
